theme: jekyll-theme-minimal
languageCode: fr-FR
title: La<br>Boua<br>Bouate
logo: logo.png
description: Administrateur système & lead consultant chez METSYS
linkedin: https://www.linkedin.com/in/leo-bouard/
# twitter: https://twitter.com/
