title: LaBouaBouate
author: Léo Bouard
languageCode: fr-FR
linkedin: https://www.linkedin.com/in/leo-bouard/
credly: https://www.credly.com/users/leo-bouard/badges/
emailAddress: leo.bouard@hotmail.com
include: [_pages]