# Author information
title: LaBouaBouate
author: Léo Bouard
languageCode: fr-FR
linkedin: https://www.linkedin.com/in/leo-bouard/
credly: https://www.credly.com/users/leo-bouard/badges/
emailAddress: leo.bouard@hotmail.com

# Add '_pages' folders
include: [_pages]

# Kramdown Configuration      
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# SASS configuration
sass:
    sass_dir: _sass
    style: compressed

# Default layouts per folder 
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: page

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist