theme: jekyll-theme-minimal
languageCode: fr-FR
title: Léo Bouard
logo: logo.png
description: Administrateur système & lead consultant chez METSYS
github:
  zip_url: http://example.com/download.zip
  another_url: another value
