theme: jekyll-theme-minimal
languageCode: fr-FR
title: Léo Bouard
# logo: logo.png
description: Administrateur système & lead consultant chez METSYS #[METSYS](https://www.linkedin.com/company/metsys/)
