# Author information
title: LaBouaBouate
author: Léo Bouard
languageCode: fr-FR
linkedin: https://www.linkedin.com/in/leo-bouard/
credly: https://www.credly.com/users/leo-bouard/badges/
emailAddress: leo.bouard@hotmail.com

# Add '_pages' folder
include: [_pages]

# Kramdown configuration      
markdown: kramdown
highlighter: rouge

# SASS configuration
sass:
    sass_dir: _sass
    style: compressed

# Default layouts per folder 
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: page

# Google Analytics
google_analytics: G-C2NF11X1GL