theme: jekyll-theme-minimal
languageCode: fr-FR
title: Léo Bouard
logo: https://media-exp1.licdn.com/dms/image/C4D03AQFS91lr-DUEmg/profile-displayphoto-shrink_200_200/0/1614265144634?e=2147483647&v=beta&t=EPOcofUrnqBsT9v0_5PZj3WNDtyC9MAso_wfgg730sY
